name: 'Setup SwiftWasm'
description: 'Download a SwiftWasm toolchain and add it to the PATH'
branding:
  color: orange
  icon: download
inputs:
  swift-version:
    description: 'Swift version to configure (default: wasm-5.7.1-RELEASE)'
    required: true
    default: 'wasm-5.7.1-RELEASE'
runs:
  using: 'node16'
  main: 'dist/index.js'
